# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b53daee9eee3b26c9204d207769505a77bad8dbef8ead321e7504b3fb8acd6efaf7e0860543ddd3327ae837cdf2dc378ea248e35a41d5e45d943d9168e97dd38

test:
  secret_key_base: 630373281d6a36b5467556698372ccdfa66e31b33fca4a3a2fe79f24e5a85775fa7042fe91fc3b1abbff771df8180d4020987609105b6e715e99ad4de1ac89dd

preview:
  secret_key_base: 8d3659582e20d2203b241ad6eff9df34549e4722ef906a435cc528fc8a73a0343231264d0475c9850bad8a951edfb4eff66cf899ce5e24c1ab33c30cca2bfda6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
